//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCoreBBS.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCoreBBS.Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveNode {
            get {
                return ResourceManager.GetString("ActiveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Message Here....
        /// </summary>
        public static string EnterBody {
            get {
                return ResourceManager.GetString("EnterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string EnterSubject {
            get {
                return ResourceManager.GetString("EnterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string FooterPanelHeading {
            get {
                return ResourceManager.GetString("FooterPanelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Core Cross-Platform Forum.
        /// </summary>
        public static string HomeIndexTitle {
            get {
                return ResourceManager.GetString("HomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction To Forum.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Reply.
        /// </summary>
        public static string LastReply {
            get {
                return ResourceManager.GetString("LastReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string NewNode {
            get {
                return ResourceManager.GetString("NewNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Hot.
        /// </summary>
        public static string NobodyCaresNode {
            get {
                return ResourceManager.GetString("NobodyCaresNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Environment.
        /// </summary>
        public static string OperatingEnv {
            get {
                return ResourceManager.GetString("OperatingEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Topics.
        /// </summary>
        public static string PopularNode {
            get {
                return ResourceManager.GetString("PopularNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted On.
        /// </summary>
        public static string PostedOn {
            get {
                return ResourceManager.GetString("PostedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Thread.
        /// </summary>
        public static string SelectThread {
            get {
                return ResourceManager.GetString("SelectThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Time.
        /// </summary>
        public static string ServerTime {
            get {
                return ResourceManager.GetString("ServerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut to.
        /// </summary>
        public static string ShortcutList {
            get {
                return ResourceManager.GetString("ShortcutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky.
        /// </summary>
        public static string Sticky {
            get {
                return ResourceManager.GetString("Sticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Development.
        /// </summary>
        public static string SystemDevelopment {
            get {
                return ResourceManager.GetString("SystemDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }
    }
}
